spring.application.name=TgBotOnSpringBoot
telegram.bot.token=8037617513:AAHJA2LiEpQdHvl6nUzBq3LSXLNwGbJi7gQ
# рандомный нерабочий токен

spring.datasource.url=jdbc:postgresql://localhost:5432/Pet_Shelter
spring.datasource.username=student
spring.datasource.password=chocolatefrog
spring.jpa.hibernate.ddl-auto=validate
spring.liquibase.change-log=classpath:liquibase/changelog-master.yml
server.port = 8080